<a href="https://www.kaggle.com/code/ramakrushnamohapatra/numpy-more-than-200-cells?scriptVersionId=107006666" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

## **NumPy:**

* Will understand Numpy
* Creating and Manipulating Arrays
* Lots of cells to cover basics and Questions

**NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays**

In [39]:
print("Welcome to Numpy Tutor!!!!")

Welcome to Numpy Tutor!!!!


**NumPy Resources: https://numpy.org**

**NumPy Documentation: https://numpy.org/doc**

**SourceCode: https://github.com/numpy/numpy**

In [40]:
lst = [False, 1, 2.2, 33]
type(lst)

list

In [41]:
# Add 1 to every element of the list

# Multiply -3 to every element 

In [42]:
lst = [2,3,4,5]

print([i+1 for i in lst])

print([i*(-3) for i in lst])

[3, 4, 5, 6]
[-6, -9, -12, -15]


**To Multiply 2 Lists, it will a hectic task when data is large amount. So, Numpy was introduced.**

In [43]:
import numpy as np #when you will find Error: ModuleNotFound Error

#do pip install numpy

l1 = [1,2,3,4]
l2 = [3,4,5,6]

l1 = np.array(l1)
l2 = np.array(l2)
print(l1, l2)
print(l1*l2)
print(type(l1))

[1 2 3 4] [3 4 5 6]
[ 3  8 15 24]
<class 'numpy.ndarray'>


In [44]:

l1 = [1,2,3.2,4]
l2 = [3,4,5,6.2]

l1 = np.array(l1)
l2 = np.array(l2)
print(l1,l1.dtype, l2,l2.dtype)

l1*l2

[1.  2.  3.2 4. ] float64 [3.  4.  5.  6.2] float64


array([ 3. ,  8. , 16. , 24.8])

**The result got converted into float. Because Numpy array only store one type of data. Numpy has a priority list where its store float has a higer priority than integer.**

In [45]:
l1 = [[1,2,3],[5,9,7],[6,7,8]]
print(l1,type(l1))
print(l1[2][0]) # if want the element 6

l1 = np.array(l1)
print(l1,type(l1))

print(l1.ndim)

[[1, 2, 3], [5, 9, 7], [6, 7, 8]] <class 'list'>
6
[[1 2 3]
 [5 9 7]
 [6 7 8]] <class 'numpy.ndarray'>
2


## Range and Arange

In [46]:
print([i for i in range(10)])
print(list(range(1,10,2)))
print("\n")
arr = np.arange(10)
print(arr)
print(np.arange(1,10,2))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


## Data Of Zeros and Ones

In [47]:
print(np.zeros((4,3)))

print(np.zeros(10))

print(np.zeros(10, dtype=int))

print("\n")

print(np.ones((4,3)))
print(np.ones(10))
print(np.ones(10,dtype= int))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


## Linerly Spaced

Calculate the space: 

**Formula = (end -start)/(num-1)**

In [48]:
print(np.linspace(start = 1, stop = 5,num= 10))  ## The space here is 0.4444
print(np.linspace(1,5,10))
print("\n")
print(np.linspace(1,20,8))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


[ 1.          3.71428571  6.42857143  9.14285714 11.85714286 14.57142857
 17.28571429 20.        ]


## Identity Matrix

In [49]:
print(np.eye(5))
print("\n")
print(np.eye(5, dtype = int))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## Random Data

In [50]:
import random
print(np.random.random((4,3))) ## Random values populate over a distribution [0,1]. 
#So values will be all in floats

[[0.43244654 0.84021596 0.18682212]
 [0.7979822  0.12290948 0.03844312]
 [0.18244144 0.37861345 0.73426934]
 [0.99793079 0.14655896 0.17616984]]


In [51]:
## To Generate Integer values
print(np.random.randint(1,100,(4,3)))
# Element will lie between 1,100 and matrix will be 4*3

[[62 56 53]
 [95 57 73]
 [84  1 86]
 [29 54 24]]


In [52]:
l1 = [[1,2,3],[5,9,7],[6,7,8],[10,19,15]]
arr = np.array(l1)

print(arr, arr.dtype, type(arr))

[[ 1  2  3]
 [ 5  9  7]
 [ 6  7  8]
 [10 19 15]] int64 <class 'numpy.ndarray'>


## Shape and Reshape

In [53]:
print(arr.shape)

(4, 3)


In [54]:
print(arr.reshape((3,4)))
print(arr.reshape((2,6)))
print(arr.reshape((6,2)))

[[ 1  2  3  5]
 [ 9  7  6  7]
 [ 8 10 19 15]]
[[ 1  2  3  5  9  7]
 [ 6  7  8 10 19 15]]
[[ 1  2]
 [ 3  5]
 [ 9  7]
 [ 6  7]
 [ 8 10]
 [19 15]]


## Indexing

In [55]:
print(arr)

# elemnt 7 in 2nd row

print(arr[2,1])

# row>> [6,7,8]

print(arr[2])# 2nd row. Index starts from 0
print(arr[3][:]) # 3rd row and all columns
print(arr[1,:]) # A whole 1st row
print(arr[:,2]) # A whole 2nd column

[[ 1  2  3]
 [ 5  9  7]
 [ 6  7  8]
 [10 19 15]]
7
[6 7 8]
[10 19 15]
[5 9 7]
[ 3  7  8 15]


## Aggregate Function

In [56]:
print("Sum of whole array")

print(arr.sum())

Sum of whole array
92


In [57]:
print("Sum Per ccolumns")

print(arr[:,1].sum())
print(arr[:,2].sum())
print("\n")

print(arr.sum(axis=0))  #sum per column 

# axis =0 means Columns and axis - 1 means rows
print("\n")
print(arr.sum(axis=1))

Sum Per ccolumns
37
33


[22 37 33]


[ 6 21 21 44]


In [58]:
print(arr.max(axis=0))
print(arr.max(axis=1))
print(arr.min(axis=0))
print(arr.min(axis=1))
print(arr.mean(axis=0))
print(arr.mean(axis=1))

[10 19 15]
[ 3  9  8 19]
[1 2 3]
[ 1  5  6 10]
[5.5  9.25 8.25]
[ 2.          7.          7.         14.66666667]


## Questions:

In [59]:
#1# create an array
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]]
arr=np.arange(1,21).reshape((4,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [60]:
#2# Slice the following
# [[ 1  3  5]
#  [11 13 15]]

print(arr[::2,::2])

[[ 1  3  5]
 [11 13 15]]


You can see below while i changed the new_arr index 0 to 100, the old one also got changed. 
this is because of array broadcasting

In [61]:
arr = np.arange(10)
print(arr)

new_arr = arr[:4]
print(new_arr)

new_arr[0] = 100
print(new_arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[100   1   2   3]
[100   1   2   3   4   5   6   7   8   9]


**To Avoid that use copy()**

In [62]:
arr = np.arange(10)
print(arr)

new_arr = arr[:4].copy()
print(new_arr)

new_arr[0] = 100
print(new_arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[100   1   2   3]
[0 1 2 3 4 5 6 7 8 9]


## Array Conditionals

In [63]:
arr = np.arange(10)
print(arr)

print(arr>4)
print(arr[arr>4])

[0 1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True  True]
[5 6 7 8 9]


In [64]:
#Exercise: get even numbers from arr = np.arange(10)
print(arr[arr%2 ==0])

# Values divisible by 2 and 3

print(arr[(arr%2 ==0) & (arr%3 ==0)])

# Values divisible by 2 or 3

print(arr[(arr%2 ==0) | (arr%3 ==0)])

[0 2 4 6 8]
[0 6]
[0 2 3 4 6 8 9]


## Math

In [65]:
lst = list(range(1,11))
print(lst)

arr = np.array(lst)
print(arr)
print("\n")

print(lst + lst)
print(arr + arr)
print("\n")

# print(lst - lst) # No substraction in List
print(arr - arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 2  4  6  8 10 12 14 16 18 20]


[0 0 0 0 0 0 0 0 0 0]


In [66]:
print(arr * arr)
print(arr / arr)
print(arr // arr)

# For list all above operations will throw error called type error

[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [67]:
# print(lst + 2) #type error
print(arr + 2)

# print(lst -4) #Type error
print(arr -4)

[ 3  4  5  6  7  8  9 10 11 12]
[-3 -2 -1  0  1  2  3  4  5  6]


In [68]:
# print(lst * 4)  Type Error
print(arr * 4)
# print(lst /2) Type Error
print(arr /2)

# print(lst //2) Type Error
print(arr //2)

print(arr**0.5)

print(arr**2.714)

[ 4  8 12 16 20 24 28 32 36 40]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[0 1 1 2 2 3 3 4 4 5]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[  1.           6.56138329  19.72000793  43.05175067  78.88684582
 129.39053052 196.60568906 282.47903745 388.87871287 517.60683195]


In [69]:
from math import sqrt
print(np.sqrt(arr))
print(np.log(arr))
print(np.log2(arr))
print(np.sin(arr))
print(np.cos(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]


In [70]:
print(arr*arr)
print(arr/arr)

[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [71]:
arr = np.arange(11)

print(arr*arr)
print(arr/arr) #Throw us an Warning for 0/0  

[  0   1   4   9  16  25  36  49  64  81 100]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [72]:
print(np.nan != np.nan)

True


In [73]:
arr = np.random.randint(1,11,(15))
arr

array([ 5,  5,  3,  2,  4,  2,  2,  9,  3,  1,  2,  9, 10,  6,  4])

In [74]:
np.where(arr==7)

(array([], dtype=int64),)

In [75]:
arr = np.array([[1,2,3,4],[4,6,5,7],[7,8,9,10]])
print(arr)

print(np.where(arr == 7))

[[ 1  2  3  4]
 [ 4  6  5  7]
 [ 7  8  9 10]]
(array([1, 2]), array([3, 0]))


In [76]:
arr = np.array([np.nan,np.nan,2,3,4,np.nan])

print(np.where(arr==nan))

NameError: name 'nan' is not defined

In [ ]:
print(np.isnan(arr))
print(np.isnan(arr).sum())
print(np.where(np.isnan(arr)))

## Sorting

In [ ]:
arr = np.random.randint(1,100,15)
print(arr)
print(np.sort(arr))

In [ ]:
print(np.sort(arr)[::-1])

In [ ]:
#2<3
#-2>-3
print(np.sort(-arr))
print(-np.sort(-arr))

## Stacking

In [ ]:
# Which one is vertical
# 1 
# 2-- 

arr1 = np.random.randint(0,999,(2,3))
arr2 = np.random.randint(0,999,(2,3))

print(arr1,arr2)

In [ ]:
# Vertical stack >> No of columns should be same

print(np.vstack([arr1,arr2]))

In [ ]:
# Horizontal Stack >> No of rows should be same

print(np.hstack([arr1,arr2]))

## Questions:

In [ ]:
arr = np.array([[1,2,np.nan], [np.nan,5,np.nan],[1,np.nan,11]])
print(arr)

# Find frequency of nan values per row >> [1 2 1]
print(np.isnan(arr[0:]).sum(axis = 1))

In [ ]:
# Find rows index that have nan values >> [0, 1, 1, 2])

print(np.where((np.isnan(arr)))[0])

##### This brings to the END of this Tutorial.

##### Hope you Gained some knowldge about Numpy by now.

##### Please give me a follow and Upvote this notebook.

### THANK YOU !!!!
